### ISSUE TITLE
Unable to use default or ternary filter with vars from pattern_match

### ISSUE THREAD

**Issue by jmighion** [ansible-network/network-engine#17]
If a pattern_match doesnt find what's being looked for, the returned container `matches` is undefined. This makes us unable to reference the `matches.0` and use filters on it since `matches` is undefined. 

Example pattern_match
```yaml
- name: match duplex
  pattern_match:
    regex: "duplex (\\S+)"
    contents: "{{ item }}"
  register: duplex_mode
```
If duplex isn't found and I try to default it with something like, but it will always return null
```yaml
item.duplex_mode.matches.0 | default('auto')
```

My current workaround is an inline conditional
```yaml
'auto' if item.duplex_mode.matches is undefined else item.duplex_mode.matches.0
```
