### ISSUE TITLE
export_as: dict does not recursively update the dictionary

### ISSUE THREAD

**Issue by jmighion** [ansible-network/network-engine#22]
The update method on a dict is only a single level. There is an `_update` now in the `template/__init__.py` that should be used at https://github.com/ansible-network/network-engine/blob/devel/action_plugins/text_parser.py#L148

Not sure how that will need to be edited to get to that method since it's now in a plugin. Might need a util structure to put common methods into.

**Comment by trishnaguha** [comment]
@jmighion right that won't update the dictionary recursively, do you have any scenario that I can use to reproduce and see if we can solve that for now without having util?

**Comment by jmighion** [comment]
I believe any json template that has a static key at the top will do. Here we're modeling similar to openconfig : 

```yaml
- name: template lldp state
  loop: "{{ state_values }}"
  register: lldp
  export: yes
  export_as: dict
  json_template:
    template:
      - key: interfaces
        object:
          - key: interface
            object:
              - key: "{{ item.name.matches.0 }}"
                object:
                  - key: name
                    value: "{{ item.name.matches.0 }}"
                  - key: neighbors
                    object:
                      - key: neighbor
                        object:
                          - key: "{{ item.neighbor.matches.0 }}"
                            object:
                              - key: id
                                value: "{{ item.neighbor.matches.0 }}"
                              - key: state
                                object:
                                  - key: system-name
                                    value: "{{ item.neighbor.matches.0 }}"
                                  - key: system-description
                                    value: "{{ item.description.matches.0 }}"
                                  - key: chassis-id
                                    value: "{{ item.chassis_id.matches.0 }}"
                                  - key: id
                                    value: "{{ item.neighbor.matches.0 }}"
                                  - key: port-id
                                    value: "{{ item.port_id.matches.0 }}"
                                  - key: port-description
                                    value: "{{ item.port_desc.matches.0 }}"
                                  - key: management-address
                                    value: "{{ item.mgmt_addr.matches.0 }}"
                                  - key: management-address-v6
                                    value: "{{ item.mgmt_addr_ipv6.matches.0 }}"
```

That will return just the last item in the loop over `state_values` since the update is not recursive. If I switch to the `_update` method from https://github.com/ansible-network/network-engine/blob/devel/lib/network_engine/plugins/template/__init__.py#L64 then all the items in `state_values` will be templated.
