### ISSUE TITLE
command_parser failed to load tasks

### ISSUE THREAD

**Issue by alanzdunic** [ansible-network/network-engine#229]
# ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
ansible 2.7.8
ansible tower 3.4.1
ansible-network.network-engine 2.7.4
```

# Network OS
N/A

# SUMMARY

Currently in command_parser.py after source path is constructed tasks are still loaded from `src` [tasks = self._loader.load_from_file(src)], but with recent changes I think tasks should now load from `src_path` [tasks = self._loader.load_from_file(src_path)]

# STEPS TO REPRODUCE

```
- name: parse the show run vrf output
command_parser:
  file: "filename.yml"
  content: "{{output.stdout[0]}}"
```

# EXPECTED RESULTS

Command_parser finishes parsing successfully 

# ACTUAL RESULTS

on ansible tower playbook fails with 
```
fatal: [XXXXXXXX]: FAILED! => {"msg": "Unable to retrieve file contents\nCould not find or access '/var/lib/awx/projects/_project_name/filename.yml' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```
