### ISSUE TITLE
Retire Repo

### ISSUE THREAD

**Issue by jvanderaa** [ansible-network/network-engine#246]
# ISSUE TYPE

- Documentation Report

# ANSIBLE VERSION

N/A

# Network OS

N/A

# SUMMARY

It looks as though the functionality from this has migrated its way into the modern network libraries within Ansible. This should be documented on the repository and also on Ansible Galaxy to shift and guide to the proper location for parsing specifically.

**Comment by epicanthal** [comment]
I am currently using the 'CLI Parser Directives' functionality which seems to not work any longer when moving to Ansible 2.10.x.  So what @jvanderaa is saying is that [Network CLI Filters](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#network-cli-filters) is now the preferred method?

I am receiving the following error:
```
ERROR! Unexpected Exception, this is probably a bug: No module named 'ansible.module_utils.network_common'
```

Here are the sample tasks to reproduce:
```yaml
  tasks:
    - name: Gather current running config via ios_facts module
      cisco.ios.ios_facts:
        gather_subset:
          - config

    - name: Import the network-engine role
      import_role:
        name: ansible-network.network-engine

    - name: Parse running-config
      command_parser:
        file: my_parser.yml
        content: "{{ ansible_net_config }}"
```
