### ISSUE TITLE
Including parsers requires absolute path

### ISSUE THREAD

**Issue by jmcgill298** [ansible-network/network-engine#54]
Trying to use a parser defined in `roles/ansible-network.network-engine/parsers/nxos/`
I tried the following without success:

- `show_version.yml`
- `nxos/show_version.yml`
- `parsers/nxos/show_version.yml`
- `~/.ansible/roles/ansible-network.network-engine/parsrs/nxos/show_version.yml`

Exception:
```
fatal: [sw01]: FAILED! => {
    "msg": "src [~/.ansible/roles/ansible-network.network-engine/parsers/nxos/show_version.yml] is either missing or invalid"
}
```

Using the absolute path did work, but I would expect:
- the search path to include the `parsers` directory adjacent to the `tasks` directory
- that `~` would be acceptable to use as my home directory

It would be preferable to use the parser file name and default to `parsers/{{ ansible_network_os }}/file.[yml|yaml]`

**Comment by acozine** [comment]
Thanks for the report. It looks like you're raising three issues:
- [ ] tilde expansion (bug)
- [ ] add parsers to search path (feature request)
- [ ] potential bug with relative path usage (can we see your playbook to confirm?)

**Comment by jmcgill298** [comment]
@acozine I am fine with separating this into multiple issues; they are closely related, so I assumed the team would prefer it as one report.

I am not sure what you mean with last one as I did not try relative paths, nor did I put one in my report. I am not sure of what reference point the task would use for a relative path, so I did not try that. My directory structure is this:

~/test/galaxy/test_playbook.yml
~/test/galaxy/inventory
~/.ansible/roles/ansible-network.network-engine/
~/.ansible/roles/ansible-network.network-engine/parsers/

**Comment by trishnaguha** [comment]
@jmcgill298 Thanks for your response.

Can you please share the following information?
- The playbook
- ansible version
- network platform and version

**Comment by privateip** [comment]
@jmcgill298 the relative path question was in relation to this:

> Trying to use a parser defined in roles/ansible-network.network-engine/parsers/nxos/
I tried the following without success:

It was assumed that you are using the relative path (above) with this list from the original issue report. 

```
show_version.yml
nxos/show_version.yml
parsers/nxos/show_version.yml
~/.ansible/roles/ansible-network.network-engine/parsrs/nxos/show_version.yml
```

If the assumption is wrong, no big deal we can adjust as necessary

**Comment by jmcgill298** [comment]
- My ansible.cfg points defines my role directory as `~/.ansible/roles/`
- My playbook is in `~/test/galaxy/test_playbook.yml`
- My inventory is in `~/test/galaxy/inventory`
- My parser is in `~/.ansible/roles/ansible-network.network-engine/parsers/nxos/show_version.yml`

I would expect using "parsers/nxos/show_version.yml" to include searching for a path adjacent to the `tasks` directory of the current role (as layed out in the documentation).
I was executing ~/.ansible/roles/ansible-network.network-engine/tasks/main.yml, and expected it to look for `~/.ansible/roles/ansible-network.network-engine/parsers/nxos/show_version.yml`, which is just the current roles directory appended with the path I specified.

Mapping my search paths with @acozine suggestions:
- tilde expansion (bug) = ~/.ansible/roles/ansible-network.network-engine/parsrs/nxos/show_version.yml
- add parsers to search path (feature request) = parsers/nxos/show_version.yml and nxos/show_version.yml (honestly did not expect this last one to work, but tried since parsers/nxos/show_version.yml did not work)
-  potential bug with relative path usage (can we see your playbook to confirm?) = I don't see
Unmentioned Feature request = It would be preferable to use the parser file name and default to parsers/{{ ansible_network_os }}/file.[yml|yaml], which maps to show_version.yml

inventory (~/test/galaxy/inventory):
```
[all]
ansible_python_interpreter="python"

[nxos:vars]
ansible_user="admin"
ansible_ssh_pass="passwd"
ansible_network_os="nxos"

[nxos]
nxos_sw01 ansible_host="10.1.1.1"
```

playbook (~/test/galaxy/test_playbook.yml):
```
---
- name: "DEMO ANSIBLE NETWORK-ENGINE"
  hosts: "nxos"
  connection: "network_cli"
  gather_facts: no
  tasks:
    - name: "DEMO NETWORK-ENGINE ROLE"
      include_role:
        name: "ansible-network.network-engine"
```

ansible-network.network-engine role (~/.ansible/roles/ansible-network.network-engine/tasks/[main.yml|nxos.yml])
```
---
- name: "01 {{ inventory_hostname | upper }}: COLLECT SHOWVERSION FROM DEVICE"
  include_tasks: "{{ ansible_network_os }}.yml" # registers output from show version as version

- name: "02 {{ inventory_hostname | upper }}: PARSE SHOW DATA FROM DEVICE USING TEXT_PARSER"
  text_parser:
    # file: "parsers/{{ ansible_network_os }}/show_version.yml" This fails, but I expect it to use the role's directory, which for this role would be ~/.ansible/roles/ansible-network.network-engine/
    # file: "~/.ansible/roles/ansible-network.network-engine/parsers/nxos/show_version.yml" This fails because it does not translate ~ to my home directory
    # file: "show_version.yml" this fails, but would be convenient if you could use this when following standard directory convention laid out in docs of `parsers/{{ network_os }}/$name_of_file`
    file: "{{ absolute_path }}"
    content: "{{ version['stdout'][0] }}"
```
@privateip @trishnaguha does this help?
