### ISSUE TITLE
When conditional in json template doesn't work

### ISSUE THREAD

**Issue by jmighion** [ansible-network/network-engine#71]
# ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.2
  config file = /home/v-jamigh/git/Ansible-Networking/ansible.cfg
  configured module search path = [u'/home/v-jamigh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

# Network OS

- Operating System (inc version) of machine running Ansible
- Network device make/model, including version
Any
# SUMMARY

We're unable to use `when:` in a json_template. This is holding us back from updating to the plugin version. I saw the comment in the plugin code, making this issue to track it a little easier.

# STEPS TO REPRODUCE

```yaml
- name: template interface state
  register: interfaces_state
  loop: "{{ contents.TABLE_interface.ROW_interface  }}"
  export: yes
  export_as: dict
  json_template:
    template:
      - key: interfaces
        object:
          - key: interface
            object:
              - key: "{{ item.interface }}"
                object:
                  - key: ethernet
                    object:
                      - key: state
                        object:
                          - key: hw-mac-address
                            value: "{{ item.eth_hw_addr }}"
                          - key: duplex-mode
                            value: "{{ item.eth_duplex }}"
                          - key: port-speed
                            value: "{{ item.eth_speed  }}"
                    when: "'ethernet' in (item.interface | lower)"
```

# EXPECTED RESULTS

Only load the object when the conditional passes.
# ACTUAL RESULTS

`when` isn't check
